### ISSUE TITLE
Wrong mapping for characters Z, z in Main font

### ISSUE THREAD

**Issue by ilizol** [t-bullock/KA-ED#1]
font: KAEDMain-Regular.ttf

name: Z
unicode: 005A

name: z
unicode: 007A

![Screenshot_20200509_133710](https://user-images.githubusercontent.com/7188298/81471516-485b0e80-91fa-11ea-91bd-3f2bc0dd6363.png)
![Screenshot_20200509_133745](https://user-images.githubusercontent.com/7188298/81471517-4abd6880-91fa-11ea-9405-085e4e773c26.png)

**Comment by t-bullock** [comment]
Fixed by https://github.com/t-bullock/KA-ED/commit/6290e184d05f2981f8c7f933f7164398d18bf797
